testonly: False
with-expecter: True
all: True
resolve-type-alias: False
disable-version-string: True
issue-845-fix: True
packages:
  go-api/src/services:
    config:
      dir: .internal/mocks/mockservices
      outpkg: "mock{{.PackageName}}"
    interfaces:
      HealthcheckService:
  go-api/src/handlers:
    config:
      dir: .internal/mocks/mockhandlers
      outpkg: "mock{{.PackageName}}"
    interfaces:
      HealthcheckHandler:
  go-api/src/clients:
    config:
      dir: .internal/mocks/mockclients
      outpkg: "mock{{.PackageName}}"
    interfaces:
      PostgresClient:
  go-api/src/repositories:
    config:
      dir: .internal/mocks/mockrepositories
      outpkg: "mock{{.PackageName}}"
    interfaces:
      TaskRepository:
      CommentRepository: