// Code generated by mockery. DO NOT EDIT.

package mockhandlers

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// MockHealthcheckHandler is an autogenerated mock type for the HealthcheckHandler type
type MockHealthcheckHandler struct {
	mock.Mock
}

type MockHealthcheckHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthcheckHandler) EXPECT() *MockHealthcheckHandler_Expecter {
	return &MockHealthcheckHandler_Expecter{mock: &_m.Mock}
}

// GetAPIStatus provides a mock function with given fields: e
func (_m *MockHealthcheckHandler) GetAPIStatus(e echo.Context) error {
	ret := _m.Called(e)

	if len(ret) == 0 {
		panic("no return value specified for GetAPIStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHealthcheckHandler_GetAPIStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAPIStatus'
type MockHealthcheckHandler_GetAPIStatus_Call struct {
	*mock.Call
}

// GetAPIStatus is a helper method to define mock.On call
//   - e echo.Context
func (_e *MockHealthcheckHandler_Expecter) GetAPIStatus(e interface{}) *MockHealthcheckHandler_GetAPIStatus_Call {
	return &MockHealthcheckHandler_GetAPIStatus_Call{Call: _e.mock.On("GetAPIStatus", e)}
}

func (_c *MockHealthcheckHandler_GetAPIStatus_Call) Run(run func(e echo.Context)) *MockHealthcheckHandler_GetAPIStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *MockHealthcheckHandler_GetAPIStatus_Call) Return(_a0 error) *MockHealthcheckHandler_GetAPIStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthcheckHandler_GetAPIStatus_Call) RunAndReturn(run func(echo.Context) error) *MockHealthcheckHandler_GetAPIStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHealthcheckHandler creates a new instance of MockHealthcheckHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthcheckHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthcheckHandler {
	mock := &MockHealthcheckHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
